language: node_js
node_js:
        - "node"
script:
        - echo “toto”
        - npm update
        - npm install jshint --save-dev
        - node_modules/.bin/jshint src
        
        
deploy:
        #local_dir: docs
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
        on:
                branch: master
