language: node_js
node_js:
        - "node"
script:
        - echo “toto”
        - npm update
        - npm install jshint --save-dev
        - node_modules/.bin/jshint src
        - npm install jsdoc
        - node_modules/.bin/jsdoc src -d docs

